//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 12:44:22 PM CET 
//

package sumo.movements.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the movements.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	private final static QName _LaneTypeVehicle_QNAME = new QName("", "vehicle");
	private final static QName _SumoNetstate_QNAME = new QName("", "sumo-netstate");
	private final static QName _TimestepTypeEdge_QNAME = new QName("", "edge");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: movements.jaxb
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link SumoNetstateType }
	 * 
	 */
	public SumoNetstateType createSumoNetstateType()
	{
		return new SumoNetstateType();
	}

	/**
	 * Create an instance of {@link TimestepType }
	 * 
	 */
	public TimestepType createTimestepType()
	{
		return new TimestepType();
	}

	/**
	 * Create an instance of {@link LaneType }
	 * 
	 */
	public LaneType createLaneType()
	{
		return new LaneType();
	}

	/**
	 * Create an instance of {@link EdgeType }
	 * 
	 */
	public EdgeType createEdgeType()
	{
		return new EdgeType();
	}

	/**
	 * Create an instance of {@link VehicleType }
	 * 
	 */
	public VehicleType createVehicleType()
	{
		return new VehicleType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link VehicleType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "vehicle", scope = LaneType.class)
	public JAXBElement<VehicleType> createLaneTypeVehicle(VehicleType value)
	{
		return new JAXBElement<VehicleType>(_LaneTypeVehicle_QNAME, VehicleType.class, LaneType.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link SumoNetstateType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "sumo-netstate")
	public JAXBElement<SumoNetstateType> createSumoNetstate(SumoNetstateType value)
	{
		return new JAXBElement<SumoNetstateType>(_SumoNetstate_QNAME, SumoNetstateType.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link EdgeType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "edge", scope = TimestepType.class)
	public JAXBElement<EdgeType> createTimestepTypeEdge(EdgeType value)
	{
		return new JAXBElement<EdgeType>(_TimestepTypeEdge_QNAME, EdgeType.class, TimestepType.class, value);
	}

}
