
package road.carsystem.webservices.trafficjam;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "JamException", targetNamespace = "http://services.jamsystem.road/")
public class JamException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private JamException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public JamException_Exception(String message, JamException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public JamException_Exception(String message, JamException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: road.carsystem.webservices.trafficjam.JamException
     */
    public JamException getFaultInfo() {
        return faultInfo;
    }

}
