
package road.carsystem.webservices.trafficjam;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrafficJamServiceConnection", targetNamespace = "http://services.jamsystem.road/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrafficJamServiceConnection {


    /**
     * 
     * @param apiKey
     * @return
     *     returns java.util.List<road.carsystem.webservices.trafficjam.LaneDto>
     * @throws JamException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTrafficJams", targetNamespace = "http://services.jamsystem.road/", className = "road.carsystem.webservices.trafficjam.GetTrafficJams")
    @ResponseWrapper(localName = "getTrafficJamsResponse", targetNamespace = "http://services.jamsystem.road/", className = "road.carsystem.webservices.trafficjam.GetTrafficJamsResponse")
    @Action(input = "http://services.jamsystem.road/TrafficJamServiceConnection/getTrafficJamsRequest", output = "http://services.jamsystem.road/TrafficJamServiceConnection/getTrafficJamsResponse", fault = {
        @FaultAction(className = JamException_Exception.class, value = "http://services.jamsystem.road/TrafficJamServiceConnection/getTrafficJams/Fault/JamException")
    })
    public List<LaneDto> getTrafficJams(
        @WebParam(name = "ApiKey", targetNamespace = "")
        String apiKey)
        throws JamException_Exception
    ;

}
