//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 01:05:22 PM CET 
//

package osm.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the osm.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	private final static QName _Osm_QNAME = new QName("", "osm");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: osm.jaxb
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link OsmType }
	 * 
	 */
	public OsmType createOsmType()
	{
		return new OsmType();
	}

	/**
	 * Create an instance of {@link NdType }
	 * 
	 */
	public NdType createNdType()
	{
		return new NdType();
	}

	/**
	 * Create an instance of {@link TagType }
	 * 
	 */
	public TagType createTagType()
	{
		return new TagType();
	}

	/**
	 * Create an instance of {@link WayType }
	 * 
	 */
	public WayType createWayType()
	{
		return new WayType();
	}

	/**
	 * Create an instance of {@link NodeType }
	 * 
	 */
	public NodeType createNodeType()
	{
		return new NodeType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link OsmType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "osm")
	public JAXBElement<OsmType> createOsm(OsmType value)
	{
		return new JAXBElement<OsmType>(_Osm_QNAME, OsmType.class, null, value);
	}

}
