//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 01:05:22 PM CET 
//

package osm.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for tagType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tagType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="k" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="v" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tagType", propOrder = { "value" })
public class TagType
{

	@XmlValue
	protected String value;
	@XmlAttribute(name = "k")
	protected String k;
	@XmlAttribute(name = "v")
	protected String v;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue()
	{
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value)
	{
		this.value = value;
	}

	/**
	 * Gets the value of the k property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getK()
	{
		return k;
	}

	/**
	 * Sets the value of the k property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setK(String value)
	{
		this.k = value;
	}

	/**
	 * Gets the value of the v property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getV()
	{
		return v;
	}

	/**
	 * Sets the value of the v property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setV(String value)
	{
		this.v = value;
	}

}
