//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 11:15:27 AM CET 
//

package sumo.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for junctionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="junctionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="request" type="{}requestType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="z" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="traffic_light"/>
 *             &lt;enumeration value="right_before_left"/>
 *             &lt;enumeration value="priority"/>
 *             &lt;enumeration value="dead_end"/>
 *             &lt;enumeration value="unregulated"/>
 *             &lt;enumeration value="traffic_light_unregulated"/>
 *             &lt;enumeration value="allway_stop"/>
 *             &lt;enumeration value="priority_stop"/>
 *             &lt;enumeration value="internal"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="incLanes" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="intLanes" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shape" type="{}shapeTypeTwo" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "junctionType", propOrder = { "request" })
public class JunctionType
{

	protected List<RequestType> request;
	@XmlAttribute(name = "id", required = true)
	protected String id;
	@XmlAttribute(name = "x", required = true)
	protected float x;
	@XmlAttribute(name = "y", required = true)
	protected float y;
	@XmlAttribute(name = "z")
	protected Float z;
	@XmlAttribute(name = "type", required = true)
	protected String type;
	@XmlAttribute(name = "incLanes", required = true)
	protected String incLanes;
	@XmlAttribute(name = "intLanes", required = true)
	protected String intLanes;
	@XmlAttribute(name = "shape")
	protected String shape;

	/**
	 * Gets the value of the request property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the request property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRequest().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RequestType }
	 * 
	 * 
	 */
	public List<RequestType> getRequest()
	{
		if (request == null)
		{
			request = new ArrayList<RequestType>();
		}
		return this.request;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value)
	{
		this.id = value;
	}

	/**
	 * Gets the value of the x property.
	 * 
	 */
	public float getX()
	{
		return x;
	}

	/**
	 * Sets the value of the x property.
	 * 
	 */
	public void setX(float value)
	{
		this.x = value;
	}

	/**
	 * Gets the value of the y property.
	 * 
	 */
	public float getY()
	{
		return y;
	}

	/**
	 * Sets the value of the y property.
	 * 
	 */
	public void setY(float value)
	{
		this.y = value;
	}

	/**
	 * Gets the value of the z property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getZ()
	{
		return z;
	}

	/**
	 * Sets the value of the z property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setZ(Float value)
	{
		this.z = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType()
	{
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value)
	{
		this.type = value;
	}

	/**
	 * Gets the value of the incLanes property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIncLanes()
	{
		return incLanes;
	}

	/**
	 * Sets the value of the incLanes property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIncLanes(String value)
	{
		this.incLanes = value;
	}

	/**
	 * Gets the value of the intLanes property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIntLanes()
	{
		return intLanes;
	}

	/**
	 * Sets the value of the intLanes property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIntLanes(String value)
	{
		this.intLanes = value;
	}

	/**
	 * Gets the value of the shape property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getShape()
	{
		return shape;
	}

	/**
	 * Sets the value of the shape property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setShape(String value)
	{
		this.shape = value;
	}

}
