//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 11:15:27 AM CET 
//

package sumo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for phaseType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="phaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="duration" use="required" type="{}nonNegativeFloatType" />
 *       &lt;attribute name="minDur" type="{}nonNegativeFloatType" />
 *       &lt;attribute name="maxDur" type="{}nonNegativeFloatType" />
 *       &lt;attribute name="state" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[ryYgGoO]+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "phaseType")
public class PhaseType
{

	@XmlAttribute(name = "duration", required = true)
	protected float duration;
	@XmlAttribute(name = "minDur")
	protected Float minDur;
	@XmlAttribute(name = "maxDur")
	protected Float maxDur;
	@XmlAttribute(name = "state", required = true)
	protected String state;

	/**
	 * Gets the value of the duration property.
	 * 
	 */
	public float getDuration()
	{
		return duration;
	}

	/**
	 * Sets the value of the duration property.
	 * 
	 */
	public void setDuration(float value)
	{
		this.duration = value;
	}

	/**
	 * Gets the value of the minDur property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMinDur()
	{
		return minDur;
	}

	/**
	 * Sets the value of the minDur property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMinDur(Float value)
	{
		this.minDur = value;
	}

	/**
	 * Gets the value of the maxDur property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getMaxDur()
	{
		return maxDur;
	}

	/**
	 * Sets the value of the maxDur property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setMaxDur(Float value)
	{
		this.maxDur = value;
	}

	/**
	 * Gets the value of the state property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getState()
	{
		return state;
	}

	/**
	 * Sets the value of the state property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setState(String value)
	{
		this.state = value;
	}

}
