//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 11:15:27 AM CET 
//

package sumo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for roundaboutType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="roundaboutType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="nodes" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="edges" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "roundaboutType")
public class RoundaboutType
{

	@XmlAttribute(name = "nodes", required = true)
	protected String nodes;
	@XmlAttribute(name = "edges", required = true)
	protected String edges;

	/**
	 * Gets the value of the nodes property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNodes()
	{
		return nodes;
	}

	/**
	 * Sets the value of the nodes property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNodes(String value)
	{
		this.nodes = value;
	}

	/**
	 * Gets the value of the edges property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEdges()
	{
		return edges;
	}

	/**
	 * Sets the value of the edges property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEdges(String value)
	{
		this.edges = value;
	}

}
