//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 11:15:27 AM CET 
//

package sumo.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for tlTypeType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="tlTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="actuated"/>
 *     &lt;enumeration value="agentbased"/>
 *     &lt;enumeration value="static"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tlTypeType")
@XmlEnum
public enum TlTypeType
{

	@XmlEnumValue("actuated")
	ACTUATED("actuated"), @XmlEnumValue("agentbased")
	AGENTBASED("agentbased"), @XmlEnumValue("static")
	STATIC("static");
	private final String value;

	TlTypeType(String v)
	{
		value = v;
	}

	public String value()
	{
		return value;
	}

	public static TlTypeType fromValue(String v)
	{
		for (TlTypeType c : TlTypeType.values())
		{
			if (c.value.equals(v))
			{
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
