//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.28 at 11:15:27 AM CET 
//

package sumo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for prohibitionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="prohibitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="prohibitor" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prohibited" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prohibitionType")
public class ProhibitionType
{

	@XmlAttribute(name = "prohibitor", required = true)
	protected String prohibitor;
	@XmlAttribute(name = "prohibited", required = true)
	protected String prohibited;

	/**
	 * Gets the value of the prohibitor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProhibitor()
	{
		return prohibitor;
	}

	/**
	 * Sets the value of the prohibitor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProhibitor(String value)
	{
		this.prohibitor = value;
	}

	/**
	 * Gets the value of the prohibited property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProhibited()
	{
		return prohibited;
	}

	/**
	 * Sets the value of the prohibited property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProhibited(String value)
	{
		this.prohibited = value;
	}

}
